### ISSUE TITLE
Android validation does not work

### ISSUE THREAD

**Issue by DataGreed** [keeprocking/pyinapp#1]
The library needs some kind of API key for Android validation, though I only have p12 permission file, so it fails on setup.

What should i do?

**Comment by keeprocking** [comment]
You can find it in the app settings: go to https://play.google.com/apps/publish, then "All applications" -> choose the app -> "Services & APIs" - and there will be a looong RSA key, this is what you are looking for.

**Comment by DataGreed** [comment]
@keeprocking no there are no keys there. Just links to developer console and there are certs, but NO keys!

**Comment by keeprocking** [comment]
That's weird.

Settings should look like this:
<img width="1440" alt="screen shot 2016-08-15 at 20 52 52" src="https://cloud.githubusercontent.com/assets/5424241/17673601/eaed4690-6332-11e6-9ee6-705dd33e41fd.png">

Found a couple of links related to this issue:
- https://developer.android.com/google/play/licensing/setting-up.html
- https://support.magplus.com/hc/en-us/articles/203808818-Android-Creating-an-App-in-the-Google-Play-Developer-Console

but looks like no additional efforts should be made to obtain the key.

I suggest you to contact Google Play support if the links will not help.

**Comment by keeprocking** [comment]
Hey man, did you get this problem resolved? If so, please post here the solution - for the other ones who may face the similar issue.
