### ISSUE TITLE
Validating Google Play Receipt

### ISSUE THREAD

**Issue by mhsiddiqui** [keeprocking/pyinapp#12]
Google has an [api](https://developers.google.com/android-publisher/api-ref/purchases/subscriptions/get) to validate receipt. In pyinapp, for Google play receipt validation, no API call is used. Is it valid method or we should use API for google play case?

**Comment by keeprocking** [comment]
In fact, pyinapp just validates receipt signature. This can be done offline, without querying google api, and is enough in most cases.
Probably I'll add online checks some time in the future but there's no exact date yet.

**Comment by keeprocking** [comment]
> Is it valid method or we should use API for google play case?

It's totally up to you. Online checks, of course, are more safe but I haven't heard any "fail stories" around pyinapp.

**Comment by Alexeyisme** [comment]
Hi @keeprocking ! I'm sorry about such a question, but where do I get that signature, we need for android in-app validation? Should it be created by client app?

**Comment by keeprocking** [comment]
Hey @Alexeyisme! Yes, the signature comes from the client as well as the receipt itself but unfortunately I cannot recall where exactly it's stored - I quit working with iOS/Android almost 2.5 years ago
