### ISSUE TITLE
only AndroidTestPurchase error.

### ISSUE THREAD

**Issue by Rwf9DH3** [keeprocking/pyinapp#2]
Only Android TEST purchasing, this lib response error because no "orderId" exists in a receipt .

https://developer.android.com/google/play/billing/billing_testing.html

> Note: Test purchases don't have an orderId field. To track test purchases, you use the purchaseToken field instead

I think that this is a cause.

**Comment by keeprocking** [comment]
What do you mean by "response error"? Do you get a KeyError because there is no key "orderId" in the receipt? Or does it exist in the receipt but it's an empty string and it breaks your validation logic?

**Comment by keeprocking** [comment]
Fixed in 0.1.2 (thanks @krivyjan for the PR: https://github.com/keeprocking/pyinapp/pull/3).
