### ISSUE TITLE
google in-app purchases validation | reciept json structure

### ISSUE THREAD

**Issue by kaleemullah360** [keeprocking/pyinapp#4]
@keeprocking,

 for `google in-app purchase validation` using following receipt structure. it contains more keys than in your [test](https://github.com/keeprocking/pyinapp/blob/master/tests/test_purchase.py) file receipt. 

please guide me what structure to follow and necessary keys to pass in json format.

```
{
  "data": {
    "orderId": "587741.91766670682",
    "packageName": "com.game.pkg",
    "productId": "life_3",
    "purchaseTime": 1464695120669,
    "purchaseState": 0,
    "developerPayload": "351",
    "purchaseToken": "oofmvnfsnosqrtelxvc"
  },
  "signature": "QiqvGGww82SLj4lAWpl7kodOXY5yIbj7aC9jc7g770PrEBD8cVmun1ayPyTEWPHvXTcIebHhlEXz24FSSGh62paIvFVP8hWquxyQgjqWZ09DbxFjIxML23PORyA7sjgSBYfi/g/p6XVBr/63eNqLqXXkRJX/TNtioKHY/DXU4ohW3f2AnEYrnkUjWGB5y6mS83w1/8Fu5rMad"
}
```

**Comment by keeprocking** [comment]
I guess it should be something like this:

    receipt = {
      "data": {
        "orderId": "587741.91766670682",
        "packageName": "com.game.pkg",
        "productId": "life_3",
        "purchaseTime": 1464695120669,
        "purchaseState": 0,
        "developerPayload": "351",
        "purchaseToken": "oofmvnfsnosqrtelxvc"
      },
      "signature": "QiqvGGww82SLj4lAWpl7kodOXY5yIbj7aC9jc7g770PrEBD8cVmun1ayPyTEWPHvXTcIebHhlEXz24FSSGh62paIvFVP8hWquxyQgjqWZ09DbxFjIxML23PORyA7sjgSBYfi/g/p6XVBr/63eNqLqXXkRJX/TNtioKHY/DXU4ohW3f2AnEYrnkUjWGB5y6mS83w1/8Fu5rMad"
    }

    validator = GooglePlayValidator(...)
    purchase = validator.validate(receipt.data, receipt.signature)

**Comment by kaleemullah360** [comment]
thanks @keeprocking , I'll try that. :+1:
